name: Buscar ID Leagues Cup
on: workflow_dispatch

jobs:
  buscar-id:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar requests
        run: pip install requests
        
      - name: Ejecutar script de busqueda
        env:
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
        run: |
          cat << 'EOF' > ID.py
          import os, requests
          API_KEY = os.environ.get("API_SPORTS_KEY")
          url = "https://v3.football.api-sports.io/leagues"
          res = requests.get(url, headers={"x-apisports-key": API_KEY}, params={"search": "Leagues Cup"})
          
          datos = res.json().get("response", [])
          print(f"\nSe encontraron {len(datos)} ligas:")
          for liga in datos:
              id_liga = liga['league']['id']
              nombre = liga['league']['name']
              pais = liga['country']['name']
              print(f"👉 ID: {id_liga} | Torneo: {nombre} | País: {pais}")
          EOF
          python buscar.py
